### ISSUE TITLE
Provide more built-in Validable and combine Validable

### ISSUE THREAD

**Issue by bernard-ng** [devscast/validable#18]
It'd be great to have most common validables built-in in this package, like https://symfony.com/doc/current/validation.html

How can I combine multiple validables on the same field?

**Comment by yveskalume** [comment]
You can achieve that by creating a custom rule, https://github.com/devscast/validable/wiki#create-custom-rules

**Comment by bernard-ng** [comment]
@yveskalume combine built-in validables without creating a new one

**Comment by bernard-ng** [comment]
@yveskalume can you have a look now ? I'm done ✅
